version: "2"

services:
  quake3:
    build: .
    command: build
    ports:
        - "27960:27960/udp"
    deploy:
      resources:
        limits:
          # https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html
          cpus: '0.25'
          memory: '512m'

x-aws-logs_retention: 1
