AWSTemplateFormatVersion: 2010-09-09

Description: quake3 server -- initial stack

Resources:
  ECR:
    Type: AWS::ECR::Repository

Outputs:
  ECRURI:
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECR}"
